import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const streakData = [
    {
      id: 1,
      name: "exercise",
      count: 0,
    },
    {
      id: 2,
      name: "test",
      count: 0,
    },
  ];

  const [Streak, setStreak] = useState(streakData);

  const handleDec = (id) => {
    const curr = Streak.filter((x) => x.id === id);
    if (curr[0].count > 0) {
      const index = Streak.indexOf(curr);
      curr[0].count -= 1;
      const newStreak = [...Streak];
      newStreak[index] = curr;
      setStreak(newStreak);
    }
  };

  const handleInc = (id) => {
    const curr = Streak.filter((x) => x.id === id);
    const index = Streak.indexOf(curr);
    curr[0].count += 1;
    const newStreak = [...Streak];
    newStreak[index] = curr;
    setStreak(newStreak);
  };

  const handleReset = (id) => {
    const curr = Streak.filter((x) => x.id === id);
    const index = Streak.indexOf(curr);
    curr[0].count = 0;
    const newStreak = [...Streak];
    newStreak[index] = curr;
    setStreak(newStreak);
  };

  return (
    <>
      <nav className="navbar navbar-light bg-light">
        <div className="container-fluid justify-content-center">
          <span className="navbar-brand mb-0 h1 ">Streaks</span>
          <div className="dropdown">
            <button
              className="btn btn-secondary dropdown-toggle"
              type="button"
              id="dropdownMenuButton1"
              data-bs-toggle="dropdown"
              aria-expanded="false"
            >
              Dropdown button
            </button>
            <ul className="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              <li>
                <a className="dropdown-item" href="#">
                  Action
                </a>
              </li>
              <li>
                <a className="dropdown-item" href="#">
                  Another action
                </a>
              </li>
              <li>
                <a className="dropdown-item" href="#">
                  Something else here
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <div className="container">
        <Head>
          <title>Multi Streaks</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div
          className="col-md-12"
          style={{ justifySelf: "center", display: "flex" }}
        >
          {Streak.map((item, index) => (
            <div key={item.id} className="card mt-2 ms-2">
              <div className="card-body">
                <h5 className="card-title">{item.name}</h5>
                <div className="card-text">
                  <button
                    onClick={(id) => handleDec(item.id)}
                    className="btn btn-danger me-2"
                  >
                    -
                  </button>
                  <input
                    className="form-control"
                    readOnly={true}
                    type="text"
                    value={item.count}
                  />
                  <button
                    onClick={(id) => handleInc(item.id)}
                    className="btn btn-success ms-2"
                  >
                    +
                  </button>
                  <button
                    className="btn btn-danger ms-2"
                    onClick={(id) => handleReset(item.id)}
                  >
                    Reset
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </>
  );
}
